### ISSUE TITLE
Invoking multiple keys at the same time does not seem to register

### ISSUE THREAD

**Issue by stevenliebregt** [enigo-rs/enigo#251] opened 2023-11-25 11:19 UTC
**Describe your Question**
I am getting a message on a socket, which I turn into an optional modifier key, and a plain key. In the example, it is `Alt` + `n`. I am trying to use this to invoke an action in a game, but it seems as if the Alt is not registering correctly (it does act as if it had only received the `n`). Perhaps I'm just using the library wrong.

My calling code (simplified for this example):

```rust
let mut enigo = Enigo::new();

enigo.key_down(ModifierKey::Alt);
enigo.key_click(Key::Layout('n'));
enigo.key_up(ModifierKey::Alt);
```

**Describe your Goal**
I want it to be as if I manually pressed `Alt+n`

**Environment (please complete the following information):**

- OS: Windows 11
- Rust: 1.73
- Library Version: "0.1.3"

**Comment by pentamassiv** [comment] 2023-11-25 11:26
Your code is correct. This looks like https://github.com/enigo-rs/enigo/issues/228. What game is it? Can you try the above code in a different program (e.g Notepad). I am not sure if alt + n is a proper shortcut or if you have to change it to alt + ??? in order to be able to observe an effect.

**Comment by stevenliebregt** [comment] 2023-11-25 11:38
> Your code is correct. This looks like #228. What game is it? Can you try the above code in a different program (e.g Notepad). I am not sure if alt + n is a proper shortcut or if you have to change it to alt + ??? in order to be able to observe an effect.

Game in question is Star Citizen, I did observe some behavior in Intellij after running the code so perhaps it is the game that is at fault here

**Comment by pentamassiv** [comment] 2023-11-25 11:41
Alright, thank you for checking it. I'll close this issue as a duplicate of https://github.com/enigo-rs/enigo/issues/228 then. Unfortunately I did not yet find out why it is not working for some games :/
Any help is very much appreciated

**Closed by pentamassiv** 2023-11-25 11:41 UTC
Labels: question

**Comment by pentamassiv** [comment] 2024-04-19 10:15
I created https://github.com/enigo-rs/enigo/pull/280, which might address this issue. It would be great if you could test it to see if it fixes it.
