### ISSUE TITLE
Mouse moves to the wrong coordinates

### ISSUE THREAD

**Issue by C-Collamar** [enigo-rs/enigo#286] opened 2024-05-05 13:27 UTC
**Describe the bug**
Invoking `move_mouse`, to absolute coordinates (500, 500) for example, does not move the mouse over there. Instead, it takes my mouse to some seemingly deterministic yet incorrect coordinates.

**To Reproduce**
```rust
let mut enigo = Enigo::new(&Settings::default()).unwrap();

println!("Setting mouse coordinates to: (500, 500)");
enigo.move_mouse(500, 500, Coordinate::Abs)?;
// output: "Setting mouse coordinates to: (500, 500)"

println!("Mouse coordinates are now on: {:?}", enigo.location().unwrap());
// output: Mouse coordinates are now on: (9, 5)
```

**Expected behavior**
If I move the mouse to absolute coordinates (500, 500), and without touching my mouse, then the mouse should be on coordinates (500, 500) on the screen. I.e., the last output above should read: "Mouse coordinates are now on: (500, 500)".

**Environment (please complete the following information):**

- OS: Windows
- Rust: 1.78.0
- Library Version: 0.2

**Additional context**
The screen recording below is me running the program above. Notice the location of my mouse cursor as soon as it executes. For context, my screen resolution is 1280x720 (as correctly reported by [`main_display()`][1]).

https://github.com/enigo-rs/enigo/assets/19512843/11bc3dff-6d5b-4a20-9358-d0039fe3dbba

[1]: https://docs.rs/enigo/0.2.0/enigo/trait.Mouse.html#tymethod.main_display

**Comment by iwanders** [comment] 2024-05-05 17:29
@C-Collamar , I ran into the same issue, there's a PR up for this: https://github.com/enigo-rs/enigo/pull/284

**Comment by iwanders** [comment] 2024-05-11 00:01
@DayBr3ak , I think the issue is specific to Windows, see https://github.com/enigo-rs/enigo/pull/284, if you have time, please try the code changes in that PR and report on the PR whether that solves the issue for you.

**Comment by coolstudio1678** [comment] 2024-05-16 01:47
same issue on windows

**Comment by pentamassiv** [comment] 2024-05-16 12:03
Should be fixed now. Sorry about the regression. A new version is available on crates.io

**Closed by pentamassiv** 2024-05-16 12:03 UTC
Labels: bug, needs investigation
