### ISSUE TITLE
Special characters are not working with ShiftKey

### ISSUE THREAD

**Issue by antonydevadoss** [enigo-rs/enigo#295] opened 2024-06-05 09:53 UTC
**Describe the bug**
Special Characters are not typed by using shift key

**To Reproduce**
```Go
use std::thread;
use std::time::Duration;
use enigo::*;

fn main() {
    let text = "hello12345";
    let mut enigo = Enigo::new();
    for (_, letter) in text.chars().enumerate() {
        enigo.key_down(Key::Shift);
        enigo.key_click(Key::Layout(letter));
        enigo.key_up(Key::Shift);
        thread::sleep(Duration::from_millis(100));
    }
}
```

**Expected behavior**
The letters `HELLLO!@#$%` should be typed. But actually, it types "HELLO12345"

**Environment (please complete the following information):**

- OS: macOs
- Rust: rustc 1.78.0 (9b00956e5 2024-04-29)
- Library Version: enigo 0.0.14

**Additional context**
I want to simulate all keyboard inputs (special characters, capital letters) with Shift key. Could you please help on this issue?

**Comment by pentamassiv** [comment] 2024-09-10 14:06
This is the same issue as https://github.com/enigo-rs/enigo/issues/307. Even though this issue was opened before 307, I am closing this one because it is based on an old version of enigo. The issue is still present in recent versions though.

**Closed by pentamassiv** 2024-09-10 14:06 UTC
Labels: bug, macOS, needs investigation
