### ISSUE TITLE
mouse cannot scroll with diff version

### ISSUE THREAD

**Issue by Alex-Beng** [enigo-rs/enigo#202] opened 2023-09-11 04:16 UTC
**Describe your Question**
I use the enigo to simulate mouse scroll and keyboard click in [my project](github.com/Alex-Beng/Yap).  Days ago, I update the enigo version from `0.0.13` to `0.1.2`, then the wired  things appended, It could not sim the mouse scroll.

then I look into the diff in two versions:

```rust
    // 0.0.13
    fn mouse_scroll_y(&mut self, length: i32) {
        mouse_event(MOUSEEVENTF_WHEEL, unsafe { transmute(length * 120) }, 0, 0);
    }
    // 0.1.2 (actually which is the same with latest version)
    fn mouse_scroll_y(&mut self, length: i32) {
        mouse_event(MOUSEEVENTF_WHEEL, length * -120, 0, 0);
    }

```

I modify  the `0.1.2`'s code back to `0.0.13` ways. I just wonder what is the difference between the codes.

**Describe your Goal**
I just wonder what is the difference between the codes.

**Environment (please complete the following information):**

- OS: Windows 10
- Rust: rustc 1.72.0 (5680fa18f 2023-08-23)
- Library Version: enigo 0.1.2

**Comment by pentamassiv** [comment] 2023-09-11 15:37
That's odd, I cannot reproduce it. I usually open Firefox and open a website where you can scroll horizontally and vertically. Then I run the `mouse` example and check if everything worked. Can you try cloning the repo and then running `cargo run --example mouse`? It will move the mouse, click and scroll, so it would be good to open a program where you can observe the effects and see if it works.
My guess is that it is not related to the code snippet you pasted but has something to do with https://github.com/enigo-rs/enigo/issues/172

**Comment by Alex-Beng** [comment] 2023-09-11 15:40
yes, actually i use it in a video game with direct input mode. let me try the example

**Comment by Alex-Beng** [comment] 2023-09-11 16:00
i also cannot reproduce the problem now

**Comment by pentamassiv** [comment] 2023-09-11 16:14
Did you test it with Firefox, Genshin Impact or both?

**Comment by Alex-Beng** [comment] 2023-09-11 16:15
both work fine.

**Comment by pentamassiv** [comment] 2023-09-11 16:15
Okay, great. Can we close this then?

**Comment by Alex-Beng** [comment] 2023-09-11 16:19
for now, just close it. Thanks for your reply

**Closed** 2023-09-11 16:19 UTC
Labels: question
